from shop.models import Item, Purchase
from django.utils import timezone

i = Item(name="ASUS", price=455)
i.save()
i = Item(name="Lenova", price=555)
i.save()
i = Item(name="Play station", price=625)
i.save()
i = Item(name="Boots", price=80)
i.save()
i = Item(name="TV", price=500)
i.save()

i=Item.objects.get(id=1)
p=Purchase.objects.create(name="Belek", age=48, item=i, purchase_date=timezone.now())
p=Purchase.objects.create(name="Manas", age=32, item=i, purchase_date=timezone.now())
i=Item.objects.get(id=2)
p=Purchase.objects.create(name="Aman", age=22, item=i, purchase_date=timezone.now())
p=Purchase.objects.create(name="Erlan", age=25, item=i, purchase_date=timezone.now())
i=Item.objects.get(id=3)
p=Purchase.objects.create(name="Aida", age=20, item=i, purchase_date=timezone.now())
p=Purchase.objects.create(name="Bermet", age=23, item=i, purchase_date=timezone.now())
i=Item.objects.get(id=4)
p=Purchase.objects.create(name="Nursultan", age=27, item=i, purchase_date=timezone.now())
p=Purchase.objects.create(name="Baizak", age=23, item=i, purchase_date=timezone.now())
i=Item.objects.get(id=5)
p=Purchase.objects.create(name="Azamat", age=18, item=i, purchase_date=timezone.now())
p=Purchase.objects.create(name="Atai", age=22, item=i, purchase_date=timezone.now())
